version: "3"
services:
  frontend:
    container_name: toolbox_frontend
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: "Dockerfile"
    volumes:
      - ./src:/app/src
      - ./public/assets:/app/public/assets
    ports:
      - '8080:3000'
